import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Figtree } from "next/font/google";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${figtree.variable} font-sans`}>
      <body className={geist.className}>{children}</body>
    </html>
  );
}
